import Foundation

extension LocalizationManager {
    static let traditionalChineseTranslations: [LocalizationKey: String] = {
        var translations: [LocalizationKey: String] = [
            .noAppsFound: "找不到任何應用程式",
            .searchPlaceholder: "搜尋",
            .renameSearchPlaceholder: "搜尋應用程式",
            .customTitlePlaceholder: "輸入自訂名稱",
            .customTitleHint: "可在這裡重新命名任何應用程式；即使重新匯入或切換本地化語言也會保留。",
            .customTitleDefaultFormat: "預設：%@",
            .customTitleReset: "恢復預設",
            .customTitleAddButton: "新增應用程式",
            .customTitleAddFromFolder: "新增應用程式",
            .loadMore: "載入更多",
            .customTitleEmptyTitle: "目前沒有自訂名稱",
            .customTitleEmptySubtitle: "點擊按鈕選擇應用程式即可開始重新命名；重新匯入或切換語言都會保留這些設定。",
            .customTitleNoResults: "沒有符合項目",
            .customTitlePickerMessage: "選擇一個應用程式來管理顯示名稱。",
            .customTitleEdit: "編輯",
            .customTitleSave: "儲存",
            .customTitleCancel: "取消",
            .customTitleOnly: "只顯示已編輯名稱的應用程式。",
            .loadingApplications: "正在載入應用程式…",
            .showFPSOverlay: "顯示 FPS",
            .showFPSOverlayDisclaimer: "目前數值僅供參考，可能與實際影格率有差異。",
            .showFPSOverlayWarning: "開啟後會明顯增加 CPU 與記憶體用量，這是測試功能，日常使用請勿開啟。",
            .customIconTitle: "應用程式圖示",
            .customIconChoose: "選擇…",
            .customIconReset: "恢復預設圖示",
            .customIconHint: "建議使用 512×512 的 PNG/ICNS 檔案，修改會立即生效。",
            .customIconError: "無法載入所選圖片。",
            .pageIndicatorOffsetLabel: "頁面指示器間距",
            .pageIndicatorTopPaddingLabel: "頁面指示器上方間距",
            .layoutModeScopeFullscreen: "全螢幕",
            .layoutModeScopeCompact: "精簡",
            .indicatorOfflineDisplay: "離線顯示器",
            .indicatorOfflineBadge: "離線",
            .indicatorScreenIDFormat: "ID %@",
            .defaultOption: "預設",
            .customOption: "自訂",
            .perDisplayIndicatorPositionTitle: "依顯示器分別設定指示器位置",
            .perDisplayIndicatorPositionDescription: "為每台顯示器使用不同數值。",
            .applyDefaultsToCurrentDisplay: "將預設值套用到目前顯示器",
            .appTitle: "LaunchNext",
            .modifiedFrom: "基於 LaunchNow 1.3.1 修改",
            .backgroundHint: "保持背景執行：可將 LaunchNext 固定在 Dock，或使用快捷鍵開啟視窗",
            .classicMode: "經典 Launchpad（全螢幕）",
            .iconSize: "圖示大小",
            .iconsPerRow: "每列圖示數量",
            .rowsPerPage: "每頁列數",
            .iconHorizontalSpacing: "水平間距",
            .iconVerticalSpacing: "垂直間距",
            .labelFontSize: "標籤字體大小",
            .iconLabelFontWeight: "圖示文字粗細",
            .folderDropZoneSize: "資料夾目標區域大小",
            .folderDropZoneSizeHint: "降低此數值可減少在視窗模式拖曳時誤建資料夾的機率。",
            .folderDropZoneSizeWithDefault: "資料夾目標區域大小（預設 %.1fx）",
            .smaller: "更小",
            .larger: "更大",
            .predictDrop: "啟用落點預判",
            .showLabels: "顯示圖示文字",
            .useLocalizedThirdPartyTitles: "使用本地化應用程式名稱",
            .enableAnimations: "啟用滑動動畫",
            .windowOpenAnimationTitle: "視窗開關動畫",
            .followScrollPagingTitle: "跟手翻頁",
            .followScrollPagingDescription: "精準捲動時頁面會跟隨手勢移動（預設關閉）。",
            .reverseWheelPagingTitle: "反轉滾輪翻頁方向",
            .hideDockOption: "隱藏 Dock",
            .hideMenuBarOption: "全螢幕時隱藏選單列",
            .hideMenuBarInfoBody: "開啟後 Dock 也會一起隱藏。macOS 要求隱藏選單列時必須同時隱藏 Dock。",
            .hoverMagnification: "游標停留放大效果",
            .hoverMagnificationScale: "游標停留放大倍率",
            .activePressEffect: "按下縮放回饋",
            .activePressScale: "按下縮放倍率",
            .animationDurationLabel: "滑動動畫時間",
            .gridSizeChangeWarning: "調整格狀設定可能導致部分圖示位置改變。",
            .pageIndicatorHint: "若間距變化不明顯，可下調頁面指示點的位置。",
            .rememberPageTitle: "記住上次開啟的頁面",
            .globalShortcutTitle: "快捷鍵與手勢",
            .globalShortcutDescription: "使用全域快捷鍵可快速開啟或關閉 LaunchNext。",
            .shortcutSetButton: "設定快捷鍵",
            .shortcutSaveButton: "儲存",
            .shortcutClearButton: "清除",
            .shortcutNotSet: "尚未設定",
            .shortcutListening: "等待按鍵…",
            .shortcutCapturePrompt: "按下想要的快捷鍵組合，按 Esc 取消。",
            .shortcutNoModifierWarning: "未使用輔助按鍵可能會與其他應用程式衝突。",
            .dockDragSectionTitle: "將應用程式拖曳到 Dock",
            .dockDragSectionDescription: "選擇拖曳到 Dock 的觸發邊緣，並設定在 LaunchNext 交給 macOS 前需要拖曳的距離。",
            .dockDragEnabledTitle: "啟用拖曳到 Dock",
            .dockDragSideTitle: "Dock 位置",
            .dockDragTriggerDistanceTitle: "觸發距離",
            .dockDragDisabled: "關閉",
            .dockDragSideBottom: "底部",
            .dockDragSideLeft: "左側",
            .dockDragSideRight: "右側",
            .hotCornerSectionTitle: "熱點角落",
            .hotCornerSectionDescription: "當游標移到所選螢幕角落時開啟 LaunchNext。",
            .hotCornerEnabledTitle: "啟用熱點角落",
            .hotCornerToggleWhenOpenTitle: "已開啟時關閉",
            .hotCornerPositionTitle: "角落位置",
            .hotCornerTriggerDelayTitle: "觸發延遲",
            .hotCornerHitboxSizeTitle: "觸發區域",
            .gestureSectionTitle: "手勢",
            .gestureSectionDescription: "實驗性的觸控板捏合與輕點手勢，可用於 LaunchNext。",
            .gestureEnabledTitle: "啟用捏合手勢",
            .gestureCloseOnPinchOutTitle: "張開手勢關閉",
            .gestureTapActionTitle: "輕點手勢",
            .gestureFingerCountTitle: "手勢手指數",
            .gestureFingerCountFour: "4 指",
            .gestureFingerCountFive: "5 指",
            .gestureTapActionOff: "關閉",
            .gestureTapActionOpen: "開啟",
            .gestureTapActionToggle: "切換",
            .gestureInputDeviceTitle: "手勢輸入裝置",
            .gestureInputDeviceModeAuto: "自動",
            .gestureInputDeviceModeSelected: "指定裝置",
            .gestureInputDeviceAutoDescription: "監聽所有可用觸控板，並使用最先觸發有效手勢的裝置。",
            .gestureInputDeviceManualEmpty: "請至少選擇一個觸控板。",
            .gestureInputDeviceBuiltInBadge: "內建",
            .gestureInputDeviceExternalBadge: "外接",
            .gestureInputDeviceUnavailableDescription: "部分已選裝置目前無法使用。請重新連接它們，或改選其他觸控板。",
            .gestureSystemHintTitle: "觸控板設定",
            .gestureSystemHintBody: "使用此手勢前，請先到 系統設定 > 觸控板 > 更多手勢 中關閉「顯示桌面」。",
            .hotCornerPositionTopLeft: "左上角",
            .hotCornerPositionTopRight: "右上角",
            .hotCornerPositionBottomLeft: "左下角",
            .hotCornerPositionBottomRight: "右下角",
            .scrollSensitivity: "捲動靈敏度",
            .low: "低",
            .high: "高",
            .importSystem: "匯入系統 Launchpad",
            .importLegacy: "匯入 Legacy (.lmy)",
            .importTip: "提示：點擊「匯入系統 Launchpad」即可直接匯入原生佈局。",
            .onboardingTitle: "先完成 LaunchNext 初始設定",
            .onboardingSubtitle: "先選擇一項初始化操作，再開始載入並算繪所有應用程式圖示。",
            .exportData: "匯出資料",
            .importData: "匯入資料",
            .dataManagementTitle: "資料管理",
            .layoutPresetTitle: "預設佈局",
            .layoutPresetDescription: "套用一組 macOS 26 風格的預設排列。缺少的應用程式會自動跳過，其餘應用程式會追加到後方。",
            .layoutPresetApplyButton: "套用經典佈局預設",
            .layoutPresetAppliedTitle: "已套用預設",
            .layoutPresetAppliedMessage: "預設佈局已套用到目前應用程式列表。",
            .layoutPresetApplyFailedMessage: "找不到可用應用程式，無法套用此預設。",
            .layoutPresetOtherFolderTitle: "其他",
            .refresh: "重新整理",
            .showQuickRefreshButton: "顯示快速重新整理按鈕",
            .launchAtLoginTitle: "開機靜默啟動",
            .launchAtLoginDescription: "登入後自動在背景啟動 LaunchNext，視窗保持隱藏，可隨時用快捷鍵叫出。",
            .lockLayoutTitle: "鎖定佈局",
            .lockLayoutDescription: "啟用後將禁止拖曳圖示或資料夾，關閉後可繼續調整。",
            .scanSourcesIntroTitle: "管理額外的應用程式來源",
            .scanSourcesIntroDescription: "在這裡新增外接磁碟或自訂資料夾，讓其中的應用程式自動顯示在 LaunchNext。",
            .scanSourcesPlaceholder: "功能即將推出：可在此新增或移除自訂目錄，LaunchNext 會自動掃描並保持同步。",
            .scanSourcesDefaultListTitle: "系統目錄",
            .scanSourcesCustomListTitle: "自訂目錄",
            .scanSourcesAddButton: "新增目錄…",
            .scanSourcesResetButton: "恢復預設",
            .scanSourcesEmptyHint: "還沒有自訂目錄，新增後可同步更多應用程式。",
            .scanSourcesMissingBadge: "未掛載",
            .missingAppBadge: "離線",
            .resetLayout: "重置佈局",
            .resetAppearanceSettings: "重置外觀分頁設定",
            .resetAlertTitle: "確定要重置佈局？",
            .resetAlertMessage: "這會完全重置佈局：刪除所有資料夾、清除已儲存順序並重新掃描應用程式。所有自訂內容都會遺失。",
            .resetAppearanceAlertTitle: "重置外觀分頁設定？",
            .resetAppearanceAlertMessage: "這會將「外觀」分頁中的設定恢復為預設值，但不會變更你的佈局或資料夾。",
            .resetConfirm: "重置",
            .cancel: "取消",
            .quit: "結束",
            .languagePickerTitle: "語言",
            .appearanceModeTitle: "外觀模式",
            .appearanceModeFollowSystem: "跟隨系統",
            .appearanceModeLight: "淺色",
            .appearanceModeDark: "深色",
            .backgroundMaskTitle: "背景遮罩",
            .backgroundMaskLightLabel: "淺色模式遮罩",
            .backgroundMaskDarkLabel: "深色模式遮罩",
            .folderPreviewHighResTitle: "高解析度資料夾預覽",
            .folderPreviewHighResHint: "以 Retina 像素算繪資料夾圖示，更清晰（會使用更多記憶體）。",
            .folderLayoutTitle: "資料夾佈局",
            .folderLayoutDescription: "選擇資料夾內應用程式的顯示方式。",
            .folderLayoutPaged: "分頁",
            .folderLayoutVertical: "垂直捲動",
            .folderWindowWidth: "資料夾視窗寬度",
            .folderWindowHeight: "資料夾視窗高度",
            .folderWindowSizeHint: "僅在非經典模式下生效；經典全螢幕使用固定佈局。",
            .versionPrefix: "版本 ",
            .versionLabelFormat: "版本 %@",
            .versionFallback: "未知",
            .updatesHeroUpdateAvailable: "有可用更新",
            .updatesHeroUpToDate: "已是最新版本",
            .aboutProjectLink: "專案首頁",
            .aboutReportBug: "回報問題",
            .aboutContribute: "參與貢獻",
            .aboutBlog: "部落格",
            .aboutInfoSystemTitle: "作業系統",
            .aboutInfoMacOSLabel: "macOS 版本",
            .aboutInfoMacOSValueFormat: "macOS %d.%d.%d",
            .aboutInfoProcessorTitle: "處理器資訊",
            .aboutInfoChipLabel: "晶片",
            .aboutInfoDisplayTitle: "顯示器",
            .aboutInfoUnknownChip: "未知晶片",
            .aboutInfoUnknownDisplay: "未知",
            .aboutInfoDisplayGeneric: "顯示器",
            .sidebarIconSizeTitle: "側邊欄圖示大小",
            .sidebarIconSizeLarge: "大",
            .sidebarIconSizeMedium: "中",
            .languageNameSystem: "跟隨系統",
            .languageNameEnglish: "英語",
            .languageNameChinese: "中文",
            .languageNameJapanese: "日語",
            .languageNameKorean: "韓語",
            .languageNameFrench: "法語",
            .languageNameSpanish: "西班牙語",
            .languageNameItalian: "義大利語",
            .languageNameCzech: "捷克語",
            .languageNameGerman: "德語",
            .languageNameRussian: "俄語",
            .languageNameHindi: "印地語",
            .languageNameVietnamese: "越南語",
            .folderNamePlaceholder: "資料夾名稱",
            .viewOnGitHub: "開啟專案連結",
            .chooseButton: "選擇",
            .exportPanelMessage: "選擇一個目標資料夾來匯出 LaunchNext 資料",
            .importPrompt: "匯入",
            .importPanelMessage: "請選擇先前由 LaunchNext 匯出的資料夾",
            .legacyArchivePanelMessage: "請選擇 Legacy Launchpad 封存檔（.lmy/.zip）或 db 檔案",
            .importSuccessfulTitle: "匯入成功",
            .importFailedTitle: "匯入失敗",
            .okButton: "確定",
            // 更新檢查相關,
            .checkForUpdates: "檢查更新",
            .checkForUpdatesButton: "檢查更新",
            .checkingForUpdates: "正在檢查更新...",
            .upToDate: "已是最新版本",
            .updateAvailable: "發現新版本",
            .newVersion: "新版本：",
            .downloadUpdate: "下載更新",
            .updateCheckFailed: "更新檢查失敗",
            .tryAgain: "重試",
            .autoCheckForUpdates: "自動檢查更新",
            .versionParseError: "版本解析錯誤",
            .updatesRefreshButton: "重新檢查",
            .openUpdaterConfig: "開啟更新設定檔",
            .updaterConfirmTitle: "使用終端機安裝更新？",
            .updaterConfirmMessage: "LaunchNext 將會結束，並在終端機中執行更新器。安裝完成後會自動重新啟動。\n\n如果右側的「下載更新」按鈕是透明的，請直接點擊。\n這是 macOS 的 bug。⬇️",
            .updaterTerminalHint: "更新會在終端機中執行，LaunchNext 將結束並自動重新啟動。",
            .updaterLaunchFailed: "無法啟動更新器（%@）。",
            .updaterMissingBinary: "應用程式套件內找不到更新器。",
            .updaterNotExecutable: "更新器檔案無法執行。",
            .updaterHoldPrompt: "更新完成後，按 Return 鍵關閉視窗，LaunchNext 會自動重新開啟。",
        ]

        translations.merge([
            .settingsSectionGeneral: "一般",
            .settingsSectionAppSources: "來源與搜尋",
            .scanSourcesFuzzySearchTitle: "模糊搜尋",
            .scanSourcesFuzzySearchDescription: "在啟動器搜尋結果中使用模糊比對。",
            .scanSourcesSearchDelayTitle: "搜尋延遲",
            .scanSourcesSearchDelayDescription: "設定啟動器搜尋在更新結果前等待的時間。",
            .settingsSectionGameController: "遊戲控制器",
            .settingsSectionAppearance: "外觀與行為",
            .settingsSectionHiddenApps: "隱藏應用程式",
            .settingsSectionUninstall: "解除安裝工具",
            .settingsSectionSound: "聲音",
            .settingsSectionTitles: "應用程式名稱",
            .settingsSectionPerformance: "效能",
            .settingsSectionBackup: "備份",
            .settingsSectionDevelopment: "開發",
            .settingsSectionUpdates: "更新",
            .settingsSectionAbout: "關於",
            .sidebarIconSizeTitle: "側邊欄圖示大小",
            .sidebarIconSizeLarge: "大",
            .sidebarIconSizeMedium: "中",
            .languageNameSystem: "跟隨系統",
            .backupPlaceholderTitle: "備份",
            .backupPlaceholderSubtitle: "在此建立、管理與還原備份。",
            .backupChooseFolderButton: "選擇備份資料夾",
            .backupCreateButton: "建立備份",
            .backupDeleteSelectedButton: "刪除所選項目",
            .backupCleanupDisclosureTitle: "清理無用歷史記錄（進階）",
            .backupCleanupIntroPrimary: "LaunchNext 會在資料庫中保留本機變更歷史記錄。應用程式本身不會使用它，但它會隨著時間增加。",
            .backupCleanupIntroSecondary: "我們不在應用程式內執行此操作，因為它具有破壞性且需要關閉資料庫。在終端機手動執行可避免誤操作。",
            .backupCleanupWarning: "重要：執行前請結束 LaunchNext，否則資料庫可能被占用。",
            .backupCleanupInstruction: "在終端機執行以下指令以清理歷史記錄並壓縮資料庫。",
            .backupCleanupCopyButton: "複製",
            .backupCleanupCopiedLabel: "已複製",
            .backupCleanupCommandDetails: "指令說明：`PRAGMA wal_checkpoint(FULL)` 會刷新 WAL，`DELETE FROM ACHANGE` 會刪除歷史記錄，`VACUUM` 會回收空間。",
            .backupNoFolderSelected: "尚未選擇備份資料夾。",
            .backupNoBackupsFound: "找不到備份。",
            .backupImportButton: "匯入",
            .backupDeleteButton: "刪除",
            .backupEstimatedSizeHint: "估算大小基於 Data.store。",
            .backupDeleteMultipleTitle: "刪除備份",
            .backupDeleteMultipleMessageFormat: "將永久刪除所選的 %d 個備份。",
            .backupDeleteSingleTitle: "刪除備份",
            .backupDeleteSingleMessage: "將永久刪除所選備份。",
            .developmentPlaceholderTitle: "開發功能預留",
            .developmentPlaceholderSubtitle: "未來將用於除錯工具或實驗功能。",
            .developmentEnableCLICodeTitle: "命令列介面",
            .developmentEnableCLICodeHint: "關閉後將阻止終端機 CLI/TUI 存取。僅在開發測試時開啟。",
            .commandLineInterfaceHelpTitle: "命令列介面",
            .commandLineInterfaceHelpBody: "開啟後會向終端機環境寫入 launchnext 的名稱；關閉時會自動移除。\nCLI：LaunchNext --cli help\nTUI：LaunchNext --tui",
            .commandLineInterfaceShowFullPathCommand: "顯示完整可執行路徑指令",
            .commandLineInterfaceAgentHint: "這個功能主要是給 Agent 使用。",
            .commandLineInterfaceRemoveCommandButton: "移除已寫入名稱",
            .commandLineInterfaceRemoveCommandDone: "已移除已寫入名稱。",
            .commandLineInterfaceRemoveCommandMissing: "找不到受管理的已寫入名稱。",
            .commandLineInterfaceRemoveCommandInfoTitle: "這個按鈕會執行什麼",
            .commandLineInterfaceRemoveCommandInfoBody: "此按鈕只會刪除受管理的 LaunchNext CLI shim（不會刪除無關檔案）：\nrm /opt/homebrew/bin/launchnext\nrm /usr/local/bin/launchnext\nrm ~/.local/bin/launchnext\nrm ~/bin/launchnext\n接著會從 ~/.zprofile 移除 LaunchNext 的 PATH 片段。",
            .developmentForceOnboardingButton: "強制顯示引導",
            .developmentForceOnboardingHint: "僅支援經典 Launchpad（全螢幕）模式。用於測試：會先關閉設定，再立即跳出 onboarding。",
            .gameControllerPlaceholderTitle: "控制器支援",
            .gameControllerPlaceholderSubtitle: "連接控制器即可像方向鍵一樣瀏覽應用程式，後續將提供更多可設定項目。",
            .gameControllerToggleTitle: "啟用控制器導覽",
            .gameControllerStatusDisabled: "控制器導覽已關閉。",
            .gameControllerStatusNoController: "尚未偵測到任何控制器。",
            .gameControllerStatusConnectedFormat: "已連接控制器：%@",
            .gameControllerQuickGuideTitle: "基本操作",
            .gameControllerQuickGuideDirection: "方向鍵或左搖桿用於移動焦點。",
            .gameControllerQuickGuideSelect: "A 鍵確認選擇。",
            .gameControllerQuickGuideCancel: "B 鍵關閉 Launchpad。",
            .gameControllerQuickGuideMenuToggle: "選單鍵切換 Launchpad。",
            .gameControllerMenuToggleTitle: "選單鍵切換 Launchpad",
            .gameControllerMenuToggleSubtitle: "效果等同快捷鍵（開啟/關閉）。",
            .soundToggleTitle: "啟用提示音效",
            .soundToggleDescription: "為 LaunchNext 的操作播放 macOS 系統提示音。",
            .soundEventLaunchpadOpen: "開啟 Launchpad",
            .soundEventLaunchpadClose: "關閉 Launchpad",
            .soundEventNavigation: "移動焦點",
            .soundPreviewButton: "試聽",
            .soundOptionNone: "無",
            .voiceToggleTitle: "啟用 Voice Over",
            .voiceToggleDescription: "使用鍵盤或控制器導覽時，由 Voice Over 朗讀目前應用程式名稱。",
            .voiceNoteMutualExclusive: "啟用 Voice Over 後，將以語音取代導覽音效。",
            .voiceAnnouncementAppFormat: "%@",
            .voiceAnnouncementFolderFormat: "資料夾：%@",
            .backgroundStyleTitle: "背景樣式",
            .backgroundStyleOptionBlur: "高斯模糊",
            .backgroundStyleOptionGlass: "液態玻璃",
            .hiddenAppsAddButton: "隱藏應用程式",
            .hiddenAppsEmptyTitle: "尚未隱藏任何應用程式",
            .hiddenAppsEmptySubtitle: "選擇一個應用程式即可將其從 LaunchNext 網格中隱藏。",
            .hiddenAppsHint: "被隱藏的應用程式不會顯示在網格中，可在此處取消隱藏。",
            .hiddenAppsRemoveButton: "取消隱藏",
            .hiddenAppsSearchPlaceholder: "搜尋隱藏的應用程式",
            .notHiddenAppsTitle: "未隱藏應用程式",
            .notHiddenAppsHint: "選擇一個應用程式將其從 LaunchNext 隱藏。",
            .notHiddenAppsSearchPlaceholder: "篩選未隱藏的應用程式",
            .contextMenuShowInFinder: "在 Finder 中顯示",
            .contextMenuCopyAppPath: "複製應用程式路徑",
            .contextMenuRenameFolder: "重新命名資料夾",
            .contextMenuDissolveFolder: "解散資料夾",
            .contextMenuUninstallWithConfiguredTool: "使用已設定的解除安裝工具解除安裝",
            .contextMenuBatchSelectApps: "批次選擇應用程式",
            .contextMenuFinishBatchSelection: "完成批次選擇",
            .uninstallSectionDescription: "在這裡指定第三方解除安裝工具（例如 AppCleaner），後續可直接開啟使用。",
            .uninstallToolPathLabel: "已選擇的解除安裝工具",
            .uninstallToolNotConfigured: "尚未選擇解除安裝工具。",
            .uninstallToolMissing: "已選擇的解除安裝工具不存在，請重新選擇。",
            .uninstallToolChooseButton: "選擇應用程式…",
            .uninstallToolClearButton: "清除",
            .uninstallToolOpenButton: "開啟解除安裝工具",
            .uninstallToolPanelTitle: "選擇解除安裝工具應用程式",
            .accessibilityPlaceholderTitle: "輔助使用設定",
            .accessibilityPlaceholderSubtitle: "我們還在設計相關選項，敬請期待。",
            .performancePlaceholderTitle: "效能面板",
            .performancePlaceholderSubtitle: "效能指標很快就會顯示在此。",
            .performanceModeTitle: "效能模式",
            .performanceModeSubtitle: "在舊版引擎與 Next 引擎之間切換。",
            .performanceModeFull: "舊版引擎",
            .performanceModeLean: "Next 引擎",
            .performanceModeDescriptionFull: "舊版引擎保留舊版快取邏輯，優先穩定。",
            .performanceModeDescriptionLean: "Next 引擎更節省記憶體，降低卡頓。",
            .performanceRendererRecommendation: "強烈建議使用此引擎。",
            .performanceModeRestartHint: "切換後需要重新啟動才會生效。",
            .performanceModeRestartTitle: "需要重新啟動",
            .performanceModeRestartMessage: "請重新啟動 LaunchNext 以套用新的效能模式。",
            .performanceRendererTitle: "Next 引擎 + Core Animation",
            .performanceRendererBadge: "實驗性",
            .performanceRendererSubtitle: "僅在 Next 引擎可用。",
            .performanceRendererWarning: "已啟用。如遇異常請關閉此選項。",
            .performanceOverviewTitle: "效能概覽",
            .performanceOverviewSubtitle: "快速查看記憶體與快取狀態。",
            .performanceMemoryLabel: "記憶體用量",
            .performanceCacheTitle: "快取狀態",
            .performanceCacheStatusValid: "快取可用",
            .performanceCacheStatusInvalid: "快取產生中",
            .performanceCacheLastUpdateLabel: "最後更新",
            .performanceCacheNever: "從未",
            .performanceCacheClearButton: "清除快取",
            .performanceCacheIconLabel: "圖示快取",
            .performanceCacheAppInfoLabel: "應用程式資訊快取",
            .performanceCacheGridLabel: "網格快取",
            .performanceCacheTotalLabel: "總快取",
            .performanceCacheCountsHint: "這些數字代表快取項目數量，並非記憶體大小。",
            .performanceCacheIconsDisabled: "Next 引擎已關閉",
            .performanceCacheLeanHint: "Next 引擎下會略過圖示快取，以降低記憶體用量與卡頓。",
            .performanceModeRecommendation: "預設建議啟用 Next 引擎（更節省記憶體、降低卡頓）。",
            .onboardingFlowWelcomeTitle: "歡迎使用 LaunchNext",
            .onboardingFlowWelcomeSubtitle: "你的 LaunchNext，由你定義。",
            .onboardingFlowProgressFormat: "步驟 %d/%d",
            .onboardingFlowPoweredBy: "RoversX / CloseX.org",
            .onboardingFlowSkip: "跳過引導",
            .onboardingFlowBack: "上一步",
            .onboardingFlowStart: "開始",
            .onboardingFlowNext: "下一步",
            .onboardingFlowDone: "完成",
            .onboardingFlowIntroTitle: "準備開始",
            .onboardingFlowIntroSubtitle: "首次啟動建議先完成這幾個初始化操作。你可以隨時跳過，後續再到設定中繼續。",
            .onboardingFlowIntroImportItem: "匯入系統佈局",
            .onboardingFlowIntroPresetItem: "套用經典預設",
            .onboardingFlowIntroShortcutItem: "設定全域快捷鍵",
            .onboardingFlowLayoutStepTitle: "第 1 步：初始化佈局",
            .onboardingFlowLayoutStepSubtitle: "可在匯入系統佈局與經典佈局預設中擇一，也可以直接進入下一步。",
            .onboardingFlowLayoutChooseMethod: "選擇一種初始化方式",
            .onboardingFlowLayoutOptionATitle: "方式 A",
            .onboardingFlowLayoutOptionASubtitle: "匯入系統 Launchpad",
            .onboardingFlowLayoutOptionADetail: "位置最接近你目前的系統佈局。",
            .onboardingFlowLayoutOptionAUnavailableDetail: "未偵測到可匯入的系統資料庫。",
            .onboardingFlowLayoutOptionAButton: "使用系統佈局",
            .onboardingFlowLayoutOptionAUnavailableButton: "目前不可用",
            .onboardingFlowLayoutOptionBTitle: "方式 B",
            .onboardingFlowLayoutOptionBSubtitle: "套用經典佈局預設",
            .onboardingFlowLayoutOptionBDetail: "適合新機快速開始，後續可繼續調整。",
            .onboardingFlowLayoutOptionBButton: "使用經典預設",
            .onboardingFlowLayoutSkipButton: "暫時跳過，直接下一步",
            .onboardingFlowShortcutStepTitle: "第 2 步：設定全域快捷鍵",
            .onboardingFlowShortcutStepSubtitle: "設定快捷鍵後，就能隨時叫出 LaunchNext，不用回到應用程式視窗。",
            .onboardingFlowShortcutStepButton: "前往設定快捷鍵",
            .onboardingFlowCompletionHeadline: "開源、輕量、可自訂",
            .onboardingFlowCompletionDescription: "你的應用程式佈局，現在由你定義。",
            .onboardingFlowSidebarStart: "開始",
            .onboardingFlowSidebarLayout: "佈局",
            .onboardingFlowSidebarShortcut: "快捷鍵",
            .onboardingFlowSidebarDone: "完成",
        ]) { _, new in new }

        return translations
    }()
}
